# Processor frequency
F_CPU = 8000000

POINTING_DEVICE_DRIVER = pmw3360

DEFAULT_FOLDER = ploopyco/trackball/rev1_005
TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE = yes
#define TAPPING_TERM 175
#define TAPPING_TERM_PER_KEY
